-- =============================================================================
-- Masters 2026 Field Seed
-- Source: Official Masters invitee criteria (past champions, world ranking, etc.)
-- Update/add players as the official field is confirmed closer to April 9
-- =============================================================================

insert into masters_field (name, country) values
-- Past Masters Champions
('Scottie Scheffler', 'USA'),
('Jon Rahm', 'ESP'),
('Phil Mickelson', 'USA'),
('Jose Maria Olazabal', 'ESP'),
('Vijay Singh', 'FIJ'),
('Mike Weir', 'CAN'),
('Angel Cabrera', 'ARG'),
('Trevor Immelman', 'RSA'),
('Zach Johnson', 'USA'),
('Charl Schwartzel', 'RSA'),
('Bubba Watson', 'USA'),
('Adam Scott', 'AUS'),
('Patrick Reed', 'USA'),
('Tiger Woods', 'USA'),
('Dustin Johnson', 'USA'),
('Hideki Matsuyama', 'JPN'),
('Sergio Garcia', 'ESP'),
('Patrick Cantlay', 'USA'),
('Rory McIlroy', 'NIR'),
('Brooks Koepka', 'USA'),

-- Top World Ranking (approx top 50)
('Xander Schauffele', 'USA'),
('Collin Morikawa', 'USA'),
('Viktor Hovland', 'NOR'),
('Tyrrell Hatton', 'ENG'),
('Tommy Fleetwood', 'ENG'),
('Shane Lowry', 'IRL'),
('Tony Finau', 'USA'),
('Cameron Smith', 'AUS'),
('Max Homa', 'USA'),
('Matt Fitzpatrick', 'ENG'),
('Brian Harman', 'USA'),
('Jason Day', 'AUS'),
('Sungjae Im', 'KOR'),
('Wyndham Clark', 'USA'),
('Akshay Bhatia', 'USA'),
('Nicolai Hojgaard', 'DEN'),
('Rasmus Hojgaard', 'DEN'),
('Tom Kim', 'KOR'),
('Keegan Bradley', 'USA'),
('Chris Kirk', 'USA'),
('Denny McCarthy', 'USA'),
('Harris English', 'USA'),
('Russell Henley', 'USA'),
('Sepp Straka', 'AUT'),
('Justin Thomas', 'USA'),
('Jordan Spieth', 'USA'),
('Rickie Fowler', 'USA'),
('Billy Horschel', 'USA'),
('Adam Hadwin', 'CAN'),
('Corey Conners', 'CAN'),
('Mackenzie Hughes', 'CAN'),
('Davis Riley', 'USA'),
('Luke List', 'USA'),
('Taylor Moore', 'USA'),
('Cam Davis', 'AUS'),
('Min Woo Lee', 'AUS'),
('Jason Scrivener', 'AUS'),
('Tom Hoge', 'USA'),
('Taylor Pendrith', 'CAN'),
('Erik van Rooyen', 'RSA'),
('Thriston Lawrence', 'RSA'),
('Adrian Meronk', 'POL'),
('Ludvig Aberg', 'SWE'),
('Robert MacIntyre', 'SCO'),
('Marcus Kinhult', 'SWE'),
('Matt Wallace', 'ENG'),
('Aaron Rai', 'ENG'),
('Callum Shinkwin', 'ENG'),
('Justin Rose', 'ENG'),
('Lee Westwood', 'ENG'),
('Ian Poulter', 'ENG'),
('Danny Willett', 'ENG'),
('Paul Casey', 'ENG'),
('Francesco Molinari', 'ITA'),
('Thomas Pieters', 'BEL'),
('Victor Perez', 'FRA'),
('Antoine Rozner', 'FRA'),
('Matthieu Pavon', 'FRA'),
('Si Woo Kim', 'KOR'),
('K.H. Lee', 'KOR'),
('Byeong Hun An', 'KOR'),
('Sahith Theegala', 'USA'),
('Jake Knapp', 'USA'),
('Nick Dunlap', 'USA'),
('Jackson Thorbjornsen', 'USA'),
('Beau Hossler', 'USA'),
('Eric Cole', 'USA'),
('Chez Reavie', 'USA'),
('Kevin Kisner', 'USA'),
('Stewart Cink', 'USA'),
('Ryan Palmer', 'USA'),
('Charley Hoffman', 'USA'),
('Mark Hubbard', 'USA'),
('Scott Stallings', 'USA'),
('Brendon Todd', 'USA'),
('Ryan Fox', 'NZL'),
('Danny Lee', 'NZL'),
('Emiliano Grillo', 'ARG'),
('Abraham Ancer', 'MEX'),
('Carlos Ortiz', 'MEX'),
('Joaquin Niemann', 'CHI'),
('Mito Pereira', 'CHI'),
('Sebastian Munoz', 'COL'),
('Camilo Villegas', 'COL'),
('Harold Varner III', 'USA'),
('Talor Gooch', 'USA'),
('Peter Malnati', 'USA')
on conflict (name) do nothing;
